name: Sync Databricks Git Folder

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  sync:
    runs-on: ubuntu-latest

    env:
      DATABRICKS_AUTH_TYPE: github-oidc
      DATABRICKS_HOST: ${{ vars.DATABRICKS_HOST }}
      DATABRICKS_CLIENT_ID: ${{ vars.DATABRICKS_CLIENT_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Databricks CLI
        uses: databricks/setup-cli@main

      - name: Update Databricks Git Folder
        run: databricks repos update 716657599096120 --branch main 